config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 5, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum:4, maximum:20}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "Es necesario iniciar sesión"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    #Añadimos paginación
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "El artículo fue creado correctamente."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "El artículo fue actualizado correctamente."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "Solo puedes modificar y eliminar tus propios artículos"
      redirect_to @article
    end
  end

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update]
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    
    def show
        @category_articles = @category.articles.paginate(page: params[:page], per_page:4)

    end
    
    def edit
    end
  
    def update
      if @category.update(category_params)
        flash[:notice] = "La categoría ha sido actualizada"
        redirect_to @category
      else
        render 'edit'
      end
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = 'Se ha iniciado sesión correctamente'
            redirect_to user
        else
            flash.now[:alert] = 'Ha ocurrido un error con los datos introducidos. Compruebe su email y su contraseña.'
            render 'new'
        end
    end
  
    def destroy
        session[:user_id] = nil
        flash[:notice] = 'Se ha cerrado la sesión'
        redirect_to root_path
    end
  
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #Iniciar sesión tras el registro (Opcional) - Otra opción es redirigir a la página de inicio de sesión
      session[:user_id]=@user.id
      flash[:notice] = "Bienvenido #{@user.username}, ¡gracias por unirte!"
      #Redirección al listado de artículos - Se puede sustituir por redirect_to login_path y no iniciar sesión
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Tu cuenta ha sido actualizada"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = " Se ha eliminado la cuenta de usuario correctamente"
    redirect_to articles_path
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "¡Solo puedes editar y/o eliminar tu perfil!"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
  <div class="container">
  <% item.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              por <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "Mostrar", article_path(article), class: "btn btn-outline-success" %>
            <br/> <br/>
            <% if article.categories.any? %>
              <p>Categorias: <%= render article.categories %>
            <% end %>
            <br/> <br/>
            <% if logged_in? && (article.user == current_user || current_user.admin?)%>
              <%= link_to "Editar", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Eliminar", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "¿Estás seguro?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', item: @article%>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Título del artículo" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Descripción del artículo" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cbox| %>
            <%= cbox.label(class:"checkbox-inline input-checkbox ml-3") {cbox.check_box(class: "checkbox") + " " + cbox.text} %>
          <% end %>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
    <%= link_to '[ Cancelar y volver al listado de artículos ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
  <h1 class="text-center mt-4">Editar artículo</h1>
  <%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listando todos los artículos</h1>
<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article', item: @articles%>
<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div> 

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Crear artículo</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
  <h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            por <%= @article.user.username if @article.user %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if @article.categories.any? %>
              <p>Categorias: <%= render @article.categories %>
            <% end %>
            <br/> <br/>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to "Editar", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to "Eliminar", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "¿Estás seguro?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category)%> &nbsp; </span>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', item: @category%>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Nombre de la categoría: " %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
    <%= link_to '[ Cancelar y volver al listado de categorías ]', categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
  <h1 class="text-center mt-4">Editar categoría</h1>
  <%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listando todas las categorías</h1>
<div align="center">
    <%= will_paginate @articles, :container => false %>
    <% @categories.each do |category| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-8 col-md-offset-4 my-auto">
                    <li class="article-title">
                        <%= link_to category.name, category_path(category) %>
                    </li> 
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Crear nueva categoría</h1>
<%= render 'shared/errors', item: @category %>
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
    <div class="control-label col-sm-2">
        <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Nombre de la categoría", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancelar y volver al listado de artículos", articles_path %> ]
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Categoría: <%= @category.name %></h1>
<div class="apple_pagination">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Editar", edit_category_path(@category), class: "btn btn-outline-info" %>
  <% end %>
  <%= will_paginate @category_articles, :container => false %>
</div>
<%= render 'articles/article', item: @category_articles%>
<div class="apple_pagination mb-4">
  <%= will_paginate @category_articles, :container => false %>
</div> 

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small class="text-white">Copyright &copy; Mi página web</small>
  </div>
</footer> 

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to "Inicio", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownArticles" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Artículos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownArticles"">
          <% if logged_in? %>
            <%= link_to "Crear nuevo artículo", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "Mostrar artículos", articles_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item active">
        <%= link_to "Artículos", articles_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Usuarios", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUsers" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Perfil <%= "(administrador)" if current_user.admin? %>- <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownUsers">
          <%= link_to "Mostrar perfil", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Editar perfil", edit_user_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Eliminar perfil", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirmation: "¿Estás seguro?" }%>
        </div>
      </li>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCategories" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categorías
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownUsers">
          <%= link_to "Ver todas las categorías", categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
          <%= link_to category.name, category_path(category), class: "dropdown-item" %>
          <% end %>
          <% if logged_in? && current_user.admin?%>
            <div class="dropdown-divider"></div>
            <%= link_to "Nueva categoría", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
        <li>
          <%= link_to "Cerrar Sesión", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar Sesión", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Registrarse", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Práctica de Ruby on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column"> 
 
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Bienvenido a la página de información</h1>

<%= link_to 'Listado de artículos', articles_path %>
<%= link_to 'Página Principal', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Práctica de Ruby on Rails</h1>
      <p class="lead">Unidad simple de jumbotron</p>
      <hr class="my-4">
      <p>Utiliza clases para la tipografía y para mantener el contenido en el área exterior</p>
      <%= link_to "Regístrate", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if item.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Los siguientes errores han evitado que el <%= item.class.name.downcase %> fuera guardado:</h4>
    <ul>
      <% item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', item: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-4 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Introduce tu nombre de usuario" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Introduce tu email" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Elige tu contraseña" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Registrarse" : "Actualizar cuenta", class: "btn btn-outline-light btn-lg") %>        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= link_to '[ Cancelar y volver al listado de artículos ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Modifica tu perfil</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-3">Probando Ruby</h1>

<div class="apple_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= pluralize(user.articles.count, "Artículo") %></p>
            <%= link_to "Ver perfil", user, class: "btn btn-outline-success" %>
            <% if logged_in?%>
              <% if user == current_user %>
                <%= link_to "Editar perfil", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Eliminar perfil", user_path(user), class: "btn btn-outline-info", method: :delete, data: {confirm: "¿Estás seguro de que quieres eliminar el perfil y los articulos asociados?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination my-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Regístrate en la página</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center my-3">Perfil de <%= @user.username %></h1>


<% if logged_in? && @user == current_user%>
  <div class="text-center mt-4">
    <%= link_to "Edita tu perfil", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>
<h3 class="text-center my-3">Artículos</h3>
<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div> 
<%= render 'articles/article'%>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div> 